"""
HTML templates for Garak enhanced reports.

Provides HTML/CSS/JS templates for generating interactive reports.
"""

from typing import Dict, List, Any
import json
import html


def generate_html_report(data: Dict[str, Any], title: str = "Garak Security Scan Report") -> str:
    """
    Generate complete HTML report from parsed data.
    
    Args:
        data: Parsed report data from GarakReportProcessor
        title: Report title
        
    Returns:
        Complete HTML document as string
    """
    metadata = data["metadata"]
    summary = data["summary"]
    probes = data["probes"]
    attempts = data["attempts"]
    vulnerable_highlights = data["vulnerable_highlights"]
    config = data.get("config", {})
    filtered_count = data.get("filtered_count", 0)
    
    # Generate sections
    executive_summary_html = _generate_executive_summary(metadata, summary, config, filtered_count)
    charts_html = _generate_charts_section(summary, probes, attempts)
    probes_table_html = _generate_probes_table(probes)
    # Removed vulnerable_highlights_html - redundant and takes too much space
    attempts_table_html = _generate_attempts_explorer(attempts)
    config_html = _generate_config_section(config)
    
    # Embed data for JavaScript
    data_json = json.dumps({
        "summary": summary,
        "probes": probes,
        "attempts": [
            {**a, "detector_scores": a["detector_scores"]} 
            for a in attempts
        ]
    })
    
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(title)}</title>
    {_get_styles()}
</head>
<body>
    <div class="container">
        <header>
            <h1>🛡️ {html.escape(title)}</h1>
            <p class="subtitle">Generated on {metadata.get('start_time', 'Unknown')}</p>
        </header>
        
        {executive_summary_html}
        {charts_html}
        {probes_table_html}
        {attempts_table_html}
        {config_html}
        
        <footer>
            <p>Generated by Garak {metadata.get('garak_version', 'unknown')} | Run ID: {metadata.get('run_id', 'unknown')}</p>
        </footer>
    </div>
    
    <script>
    // Embedded data
    const reportData = {data_json};
    
    // Pagination state
    let currentPage = 1;
    let pageSize = 50;
    let filteredRows = [];
    
    {_get_javascript()}
    </script>
</body>
</html>"""


def _get_styles() -> str:
    """Return embedded CSS styles."""
    return """
    <style>
        :root {
            --color-pass: #43a047;
            --color-fail: #e53935;
            --color-warning: #fb8c00;
            --color-info: #1e88e5;
            --color-critical: #c62828;
            --color-high: #f57c00;
            --color-medium: #fbc02d;
            --color-low: #66bb6a;
            --bg-primary: #ffffff;
            --bg-secondary: #f5f5f5;
            --text-primary: #212121;
            --text-secondary: #757575;
            --border-color: #e0e0e0;
        }
        
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: var(--text-primary);
            background: var(--bg-secondary);
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
        }
        
        header {
            background: var(--bg-primary);
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 30px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        h1 {
            font-size: 2.5rem;
            margin-bottom: 10px;
        }
        
        .subtitle {
            color: var(--text-secondary);
            font-size: 0.9rem;
        }
        
        .section {
            background: var(--bg-primary);
            padding: 30px;
            margin-bottom: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        .section-title {
            font-size: 1.8rem;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid var(--border-color);
        }
        
        /* Executive Summary */
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }
        
        .metric-card {
            background: var(--bg-secondary);
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid var(--color-info);
        }
        
        .metric-label {
            font-size: 0.9rem;
            color: var(--text-secondary);
            margin-bottom: 8px;
        }
        
        .metric-value {
            font-size: 2rem;
            font-weight: bold;
            color: var(--text-primary);
        }
        
        .risk-indicator {
            display: inline-block;
            padding: 8px 16px;
            border-radius: 20px;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 0.9rem;
        }
        
        .risk-low { background: var(--color-low); color: white; }
        .risk-medium { background: var(--color-medium); color: white; }
        .risk-high { background: var(--color-high); color: white; }
        .risk-critical { background: var(--color-critical); color: white; }
        
        /* Charts */
        .charts-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 30px;
        }
        
        .chart-wrapper {
            background: var(--bg-secondary);
            padding: 20px;
            border-radius: 8px;
        }
        
        .chart-title {
            font-size: 1.2rem;
            margin-bottom: 15px;
            font-weight: 600;
        }
        
        /* Tables */
        .table-container {
            overflow-x: auto;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid var(--border-color);
        }
        
        th {
            background: var(--bg-secondary);
            font-weight: 600;
            position: sticky;
            top: 0;
            z-index: 10;
        }
        
        .attempt-row {
            cursor: pointer;
            transition: background 0.2s;
        }
        
        .attempt-row:hover {
            background: var(--bg-secondary);
        }
        
        .details-row {
            background: #fafafa;
        }
        
        .status-pass {
            color: var(--color-pass);
            font-weight: bold;
        }
        
        .status-fail {
            color: var(--color-fail);
            font-weight: bold;
        }
        
        /* Vulnerable Highlights */
        .vulnerable-card {
            background: #fff3e0;
            border-left: 4px solid var(--color-warning);
            padding: 20px;
            margin-bottom: 15px;
            border-radius: 4px;
        }
        
        .vulnerable-card.critical {
            background: #ffebee;
            border-left-color: var(--color-critical);
        }
        
        .vulnerable-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
        }
        
        .probe-name {
            font-weight: 600;
            color: var(--text-primary);
        }
        
        .score-badge {
            background: var(--color-fail);
            color: white;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 0.85rem;
            font-weight: bold;
        }
        
        .prompt-response {
            margin: 15px 0;
        }
        
        .prompt-label, .response-label {
            font-weight: 600;
            margin-bottom: 5px;
            color: var(--text-secondary);
            font-size: 0.9rem;
        }
        
        .prompt-text, .response-text {
            background: white;
            padding: 12px;
            border-radius: 4px;
            border: 1px solid var(--border-color);
            font-family: 'Courier New', monospace;
            font-size: 0.9rem;
            white-space: pre-wrap;
            word-wrap: break-word;
        }
        
        .detector-scores {
            margin-top: 15px;
        }
        
        .detector-score-item {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid var(--border-color);
        }
        
        .detector-score-item:last-child {
            border-bottom: none;
        }
        
        /* Filters */
        .filters {
            display: flex;
            gap: 15px;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }
        
        .filter-group {
            display: flex;
            flex-direction: column;
        }
        
        .filter-label {
            font-size: 0.9rem;
            margin-bottom: 5px;
            color: var(--text-secondary);
        }
        
        select, input[type="text"], input[type="search"] {
            padding: 8px 12px;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            font-size: 0.9rem;
        }
        
        button {
            padding: 8px 16px;
            background: var(--color-info);
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 0.9rem;
            transition: background 0.3s;
        }
        
        button:hover {
            opacity: 0.9;
        }
        
        button:disabled {
            opacity: 0.5;
            cursor: not-allowed;
        }
        
        /* Pagination */
        .pagination {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin: 20px 0;
            padding: 15px;
            background: var(--bg-secondary);
            border-radius: 4px;
        }
        
        .pagination-controls {
            display: flex;
            gap: 10px;
            align-items: center;
        }
        
        .pagination-info {
            color: var(--text-secondary);
            font-size: 0.9rem;
        }
        
        .page-button {
            padding: 6px 12px;
            background: white;
            color: var(--text-primary);
            border: 1px solid var(--border-color);
            border-radius: 4px;
            cursor: pointer;
            font-size: 0.85rem;
            transition: all 0.2s;
        }
        
        .page-button:hover:not(:disabled) {
            background: var(--color-info);
            color: white;
            border-color: var(--color-info);
        }
        
        .page-button.active {
            background: var(--color-info);
            color: white;
            border-color: var(--color-info);
        }
        
        .page-size-select {
            padding: 6px 10px;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            font-size: 0.85rem;
            background: white;
        }
        
        /* Collapsible */
        .collapsible {
            cursor: pointer;
            padding: 15px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 1.1rem;
            background: var(--bg-secondary);
            border-radius: 4px;
            margin-bottom: 10px;
            transition: background 0.3s;
        }
        
        .collapsible:hover {
            background: #e0e0e0;
        }
        
        .collapsible.active {
            background: var(--color-info);
            color: white;
        }
        
        .collapsible-content {
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.3s ease-out;
        }
        
        .collapsible-content.active {
            max-height: 2000px;
        }
        
        /* Footer */
        footer {
            text-align: center;
            padding: 20px;
            color: var(--text-secondary);
            font-size: 0.85rem;
        }
        
        /* Responsive */
        @media (max-width: 768px) {
            h1 {
                font-size: 1.8rem;
            }
            
            .metrics-grid {
                grid-template-columns: 1fr;
            }
            
            .charts-container {
                grid-template-columns: 1fr;
            }
            
            .filters {
                flex-direction: column;
            }
        }
        
        /* Progress bar */
        .progress-bar {
            width: 100%;
            height: 8px;
            background: var(--bg-secondary);
            border-radius: 4px;
            overflow: hidden;
            margin-top: 10px;
        }
        
        .progress-fill {
            height: 100%;
            background: var(--color-pass);
            transition: width 0.3s;
        }
        
        .progress-fill.fail {
            background: var(--color-fail);
        }
    </style>
    """


def _get_javascript() -> str:
    """Return embedded JavaScript for interactivity."""
    return """
        // Initialize collapsibles
        document.querySelectorAll('.collapsible').forEach(button => {
            button.addEventListener('click', function() {
                this.classList.toggle('active');
                const content = this.nextElementSibling;
                content.classList.toggle('active');
            });
        });
        
        // Get filtered rows based on current filter settings
        function getFilteredRows() {
            const probeFilter = document.getElementById('probe-filter')?.value || '';
            const statusFilter = document.getElementById('status-filter')?.value || '';
            const searchText = document.getElementById('search-filter')?.value.toLowerCase() || '';
            
            const allRows = document.querySelectorAll('.attempt-row');
            const filtered = [];
            
            allRows.forEach(row => {
                const probe = row.dataset.probe || '';
                const status = row.dataset.status || '';
                const text = row.textContent.toLowerCase();
                
                const matchesProbe = !probeFilter || probe === probeFilter;
                const matchesStatus = !statusFilter || status === statusFilter;
                const matchesSearch = !searchText || text.includes(searchText);
                
                if (matchesProbe && matchesStatus && matchesSearch) {
                    filtered.push(row);
                }
            });
            
            return filtered;
        }
        
        // Apply pagination to current filtered results
        function applyPagination() {
            filteredRows = getFilteredRows();
            const totalRows = document.querySelectorAll('.attempt-row').length;
            const totalPages = Math.ceil(filteredRows.length / pageSize);
            
            // Ensure current page is valid
            if (currentPage > totalPages) {
                currentPage = Math.max(1, totalPages);
            }
            
            // Hide all rows first
            document.querySelectorAll('.attempt-row, .details-row').forEach(row => {
                row.style.display = 'none';
            });
            
            // Show only current page rows
            const startIdx = (currentPage - 1) * pageSize;
            const endIdx = Math.min(startIdx + pageSize, filteredRows.length);
            
            for (let i = startIdx; i < endIdx; i++) {
                filteredRows[i].style.display = '';
            }
            
            // Update pagination info
            updatePaginationInfo(filteredRows.length, totalRows);
            updatePaginationButtons(totalPages);
        }
        
        // Update pagination info text
        function updatePaginationInfo(filteredCount, totalCount) {
            const countEl = document.getElementById('visible-count');
            if (countEl) {
                const startIdx = (currentPage - 1) * pageSize + 1;
                const endIdx = Math.min(currentPage * pageSize, filteredCount);
                const totalPages = Math.ceil(filteredCount / pageSize);
                
                if (filteredCount === 0) {
                    countEl.innerHTML = '<span style="color: var(--color-fail);">No attempts match your filters</span> <span style="color: var(--color-warning);">- Try adjusting your filters</span>';
                } else {
                    countEl.innerHTML = `Showing <strong>${startIdx}-${endIdx}</strong> of <strong>${filteredCount}</strong> attempts (Page ${currentPage} of ${totalPages})`;
                }
            }
        }
        
        // Update pagination buttons
        function updatePaginationButtons(totalPages) {
            const prevBtn = document.getElementById('prev-page');
            const nextBtn = document.getElementById('next-page');
            const pageInfo = document.getElementById('page-info');
            
            if (prevBtn) prevBtn.disabled = currentPage === 1;
            if (nextBtn) nextBtn.disabled = currentPage >= totalPages || totalPages === 0;
            if (pageInfo) pageInfo.textContent = `Page ${currentPage} of ${totalPages}`;
            
            // Update page number buttons
            renderPageNumbers(totalPages);
        }
        
        // Render page number buttons
        function renderPageNumbers(totalPages) {
            renderPageNumbersInContainer('page-numbers', totalPages);
            renderPageNumbersInContainer('page-numbers-bottom', totalPages);
        }
        
        function renderPageNumbersInContainer(containerId, totalPages) {
            const container = document.getElementById(containerId);
            if (!container) return;
            
            container.innerHTML = '';
            
            // Show max 7 page buttons
            let startPage = Math.max(1, currentPage - 3);
            let endPage = Math.min(totalPages, startPage + 6);
            
            // Adjust if we're near the end
            if (endPage - startPage < 6) {
                startPage = Math.max(1, endPage - 6);
            }
            
            // First page
            if (startPage > 1) {
                const btn = createPageButton(1, '1');
                container.appendChild(btn);
                if (startPage > 2) {
                    const dots = document.createElement('span');
                    dots.textContent = '...';
                    dots.style.padding = '6px 12px';
                    dots.style.color = 'var(--text-secondary)';
                    container.appendChild(dots);
                }
            }
            
            // Page buttons
            for (let i = startPage; i <= endPage; i++) {
                const btn = createPageButton(i, i.toString());
                container.appendChild(btn);
            }
            
            // Last page
            if (endPage < totalPages) {
                if (endPage < totalPages - 1) {
                    const dots = document.createElement('span');
                    dots.textContent = '...';
                    dots.style.padding = '6px 12px';
                    dots.style.color = 'var(--text-secondary)';
                    container.appendChild(dots);
                }
                const btn = createPageButton(totalPages, totalPages.toString());
                container.appendChild(btn);
            }
        }
        
        // Create page button
        function createPageButton(pageNum, label) {
            const btn = document.createElement('button');
            btn.textContent = label;
            btn.className = 'page-button' + (pageNum === currentPage ? ' active' : '');
            btn.onclick = () => goToPage(pageNum);
            return btn;
        }
        
        // Navigation functions
        function goToPage(page) {
            currentPage = page;
            applyPagination();
        }
        
        function previousPage() {
            if (currentPage > 1) {
                currentPage--;
                applyPagination();
            }
        }
        
        function nextPage() {
            const totalPages = Math.ceil(filteredRows.length / pageSize);
            if (currentPage < totalPages) {
                currentPage++;
                applyPagination();
            }
        }
        
        function changePageSize() {
            const select = document.getElementById('page-size');
            if (select) {
                pageSize = parseInt(select.value);
                currentPage = 1; // Reset to first page
                applyPagination();
            }
        }
        
        // Filter and apply pagination
        function filterAttempts() {
            currentPage = 1; // Reset to first page when filtering
            applyPagination();
        }
        
        // Expand row details
        function toggleRow(uuid) {
            const details = document.getElementById('details-' + uuid);
            if (details) {
                const isHidden = details.style.display === 'none' || details.style.display === '';
                details.style.display = isHidden ? 'table-row' : 'none';
            }
        }
        
        // Initialize pagination on load
        document.addEventListener('DOMContentLoaded', function() {
            applyPagination();
        });
        
        // If DOM is already loaded
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', () => applyPagination());
        } else {
            applyPagination();
        }
        
        console.log('Garak Enhanced Report with pagination loaded successfully');
    """


def _generate_executive_summary(metadata: Dict, summary: Dict, config: Dict, filtered_count: int = 0) -> str:
    """Generate executive summary section."""
    risk_level = summary["risk_level"]
    risk_class = f"risk-{risk_level}"
    
    filtered_note = f"""
        <div style="margin-top: 15px; padding: 10px; background: #e3f2fd; border-left: 3px solid var(--color-info); border-radius: 4px; font-size: 0.9rem;">
            <strong>ℹ️ Note:</strong> {filtered_count} pre-test setup attempts were filtered out. 
            Showing only actual model output attempts (status=2).
        </div>
    """ if filtered_count > 0 else ""
    
    return f"""
    <section class="section">
        <h2 class="section-title">📊 Executive Summary</h2>
        
        <div style="margin: 20px 0;">
            <strong>Risk Level:</strong> 
            <span class="{risk_class} risk-indicator">{risk_level.upper()}</span>
        </div>
        
        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-label">Actual Attempts Analyzed</div>
                <div class="metric-value">{summary['total_attempts']}</div>
            </div>
            
            <div class="metric-card" style="border-left-color: var(--color-fail);">
                <div class="metric-label">Vulnerable Attempts</div>
                <div class="metric-value">{summary['vulnerable_attempts']}</div>
            </div>
            
            <div class="metric-card" style="border-left-color: var(--color-fail);">
                <div class="metric-label">Attack Success Rate</div>
                <div class="metric-value">{100 - summary['pass_rate']:.2f}%</div>
                <div class="progress-bar">
                    <div class="progress-fill fail" style="width: {100 - summary['pass_rate']}%"></div>
                </div>
            </div>
        </div>
        
        <div style="margin-top: 20px; padding: 15px; background: var(--bg-secondary); border-radius: 4px;">
            <strong>Model:</strong> {html.escape(config.get('model_name', 'Unknown'))} ({html.escape(config.get('model_type', 'Unknown'))})<br>
            <strong>Garak Version:</strong> {metadata.get('garak_version', 'Unknown')}<br>
            <strong>Scan Started:</strong> {metadata.get('start_time', 'Unknown')}
        </div>
    </section>
    """


def _generate_charts_section(summary: Dict, probes: List[Dict], attempts: List[Dict]) -> str:
    """Generate enhanced charts section with visual representations."""
    
    # Calculate some additional metrics
    total_pass = summary['total_attempts'] - summary['vulnerable_attempts']
    total_fail = summary['vulnerable_attempts']
    
    # Get top 5 probes by vulnerability
    top_vulnerable_probes = probes[:5]
    
    # Create donut chart for pass/fail
    pass_percentage = summary['pass_rate']
    fail_percentage = 100 - pass_percentage
    
    # Calculate the donut segments (SVG)
    # For a donut chart, we use stroke-dasharray on a circle
    radius = 70
    circumference = 2 * 3.14159 * radius
    pass_length = (pass_percentage / 100) * circumference
    fail_length = (fail_percentage / 100) * circumference
    
    return f"""
    <section class="section">
        <h2 class="section-title">📈 Visualizations</h2>
        
        <div class="charts-container">
            <!-- Donut Chart: Pass/Fail -->
            <div class="chart-wrapper">
                <h3 class="chart-title">Pass/Fail Distribution</h3>
                <div style="display: flex; gap: 30px; align-items: center;">
                    <div style="position: relative; width: 180px; height: 180px;">
                        <svg viewBox="0 0 180 180" style="transform: rotate(-90deg);">
                            <!-- Background circle -->
                            <circle cx="90" cy="90" r="{radius}" fill="none" stroke="#f0f0f0" stroke-width="20"/>
                            
                            <!-- Pass segment (green) -->
                            <circle cx="90" cy="90" r="{radius}" fill="none" 
                                    stroke="var(--color-pass)" stroke-width="20"
                                    stroke-dasharray="{pass_length} {circumference}"
                                    stroke-linecap="round"/>
                            
                            <!-- Fail segment (red) -->
                            <circle cx="90" cy="90" r="{radius}" fill="none" 
                                    stroke="var(--color-fail)" stroke-width="20"
                                    stroke-dasharray="{fail_length} {circumference}"
                                    stroke-dashoffset="-{pass_length}"
                                    stroke-linecap="round"/>
                        </svg>
                        
                        <!-- Center text -->
                        <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); text-align: center;">
                            <div style="font-size: 2rem; font-weight: bold; color: var(--text-primary);">{summary['pass_rate']:.1f}%</div>
                            <div style="font-size: 0.8rem; color: var(--text-secondary);">Pass Rate</div>
                        </div>
                    </div>
                    
                    <div style="flex: 1;">
                        <div style="margin-bottom: 15px;">
                            <div style="display: flex; align-items: center; margin-bottom: 5px;">
                                <div style="width: 16px; height: 16px; background: var(--color-pass); border-radius: 3px; margin-right: 10px;"></div>
                                <span style="font-weight: 600;">Passed</span>
                                <span style="margin-left: auto; font-weight: bold;">{total_pass}</span>
                            </div>
                            <div style="font-size: 0.85rem; color: var(--text-secondary); margin-left: 26px;">
                                {pass_percentage:.1f}% of attempts
                            </div>
                        </div>
                        
                        <div>
                            <div style="display: flex; align-items: center; margin-bottom: 5px;">
                                <div style="width: 16px; height: 16px; background: var(--color-fail); border-radius: 3px; margin-right: 10px;"></div>
                                <span style="font-weight: 600;">Failed</span>
                                <span style="margin-left: auto; font-weight: bold;">{total_fail}</span>
                            </div>
                            <div style="font-size: 0.85rem; color: var(--text-secondary); margin-left: 26px;">
                                {fail_percentage:.1f}% of attempts
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Bar Chart: Top Vulnerable Probes -->
            <div class="chart-wrapper">
                <h3 class="chart-title">Top 5 Probes by Vulnerability</h3>
                <div style="padding: 10px 0;">
                    {"".join([f'''
                    <div style="margin-bottom: 20px;">
                        <div style="display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 0.9rem;">
                            <span style="font-weight: 600; color: var(--text-primary);">{html.escape(probe['name'].split('.')[-1][:30])}</span>
                            <span style="font-weight: bold;">
                                <span style="color: var(--color-fail);">{probe['vulnerable']}</span>
                                <span style="color: var(--text-secondary);">/{probe['attempts']}</span>
                            </span>
                        </div>
                        <div style="display: flex; align-items: center; gap: 10px;">
                            <div style="flex: 1; height: 24px; background: var(--bg-secondary); border-radius: 12px; overflow: hidden; position: relative;">
                                <div style="height: 100%; background: linear-gradient(90deg, var(--color-fail), #ff6b6b); width: {(probe['vulnerable']/probe['attempts']*100) if probe['attempts'] > 0 else 0}%; transition: width 0.3s ease; border-radius: 12px;"></div>
                                <div style="position: absolute; top: 50%; left: 10px; transform: translateY(-50%); font-size: 0.75rem; font-weight: 600; color: white; text-shadow: 0 1px 2px rgba(0,0,0,0.3);">
                                    {(probe['vulnerable']/probe['attempts']*100) if probe['attempts'] > 0 else 0:.1f}%
                                </div>
                            </div>
                        </div>
                    </div>
                    ''' for i, probe in enumerate(top_vulnerable_probes)])}
                    
                    {f'<div style="margin-top: 20px; padding: 10px; background: var(--bg-secondary); border-radius: 4px; text-align: center; font-size: 0.85rem; color: var(--text-secondary);">+ {len(probes) - 5} more probes</div>' if len(probes) > 5 else ''}
                </div>
            </div>
        </div>
        
        <!-- Additional Stats Cards -->
        <div style="margin-top: 30px; display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px;">
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 8px; color: white;">
                <div style="font-size: 0.9rem; opacity: 0.9; margin-bottom: 5px;">Total Probes Tested</div>
                <div style="font-size: 2rem; font-weight: bold;">{len(probes)}</div>
            </div>
            
            <div style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); padding: 20px; border-radius: 8px; color: white;">
                <div style="font-size: 0.9rem; opacity: 0.9; margin-bottom: 5px;">Probes with Vulnerabilities</div>
                <div style="font-size: 2rem; font-weight: bold;">{sum(1 for p in probes if p['vulnerable'] > 0)}</div>
            </div>
            
            <div style="background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%); padding: 20px; border-radius: 8px; color: white;">
                <div style="font-size: 0.9rem; opacity: 0.9; margin-bottom: 5px;">Clean Probes (0 fails)</div>
                <div style="font-size: 2rem; font-weight: bold;">{sum(1 for p in probes if p['vulnerable'] == 0)}</div>
            </div>
        </div>
    </section>
    """


def _generate_vulnerable_highlights(vulnerable: List[Dict]) -> str:
    """Generate vulnerable attempts highlights."""
    if not vulnerable:
        return """
        <section class="section">
            <h2 class="section-title">✅ No Vulnerabilities Detected</h2>
            <p>All attempts passed security checks. Great job!</p>
        </section>
        """
    
    cards_html = []
    for attempt in vulnerable[:10]:  # Show top 10
        max_score = max(attempt["detector_scores"].values()) if attempt["detector_scores"] else 0.0
        is_critical = max_score > 0.7
        card_class = "vulnerable-card critical" if is_critical else "vulnerable-card"
        
        detector_scores_html = "".join([
            f"""
            <div class="detector-score-item">
                <span>{html.escape(detector)}</span>
                <span style="font-weight: bold; color: var(--color-fail);">{score:.3f}</span>
            </div>
            """
            for detector, score in attempt["detector_scores"].items()
        ])
        
        cards_html.append(f"""
        <div class="{card_class}">
            <div class="vulnerable-header">
                <span class="probe-name">🔴 {html.escape(attempt['probe'])}</span>
                <span class="score-badge">{max_score:.3f}</span>
            </div>
            
            <div style="font-size: 0.9rem; color: var(--text-secondary); margin-bottom: 10px;">
                <strong>Goal:</strong> {html.escape(attempt['goal'])}
            </div>
            
            <div class="prompt-response">
                <div class="prompt-label">Prompt:</div>
                <div class="prompt-text">{html.escape(attempt['prompt'][:500])}</div>
            </div>
            
            <div class="prompt-response">
                <div class="response-label">Response:</div>
                <div class="response-text">{html.escape(attempt['response'][:500])}</div>
            </div>
            
            {f'<div class="detector-scores"><strong>Detector Scores:</strong>{detector_scores_html}</div>' if detector_scores_html else ''}
        </div>
        """)
    
    return f"""
    <section class="section">
        <h2 class="section-title">⚠️ Vulnerable Attempts ({len(vulnerable)} total)</h2>
        <p style="margin-bottom: 20px; color: var(--text-secondary);">
            Showing the most concerning vulnerabilities detected during the scan.
        </p>
        {"".join(cards_html)}
    </section>
    """


def _generate_probes_table(probes: List[Dict]) -> str:
    """Generate probes summary table."""
    rows_html = "".join([
        f"""
        <tr>
            <td>{html.escape(probe['name'])}</td>
            <td>{probe['attempts']}</td>
            <td style="color: var(--color-fail); font-weight: bold;">{probe['vulnerable']}</td>
            <td>
                <span class="{'status-fail' if (100 - probe['pass_rate']) >= 5 else 'status-pass'}">
                    {100 - probe['pass_rate']:.2f}%
                </span>
            </td>
        </tr>
        """
        for probe in probes
    ])
    
    return f"""
    <section class="section">
        <h2 class="section-title">🔍 Probe Results</h2>
        
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>Probe Name</th>
                        <th>Total Attempts</th>
                        <th>Vulnerable</th>
                        <th>Attack Success Rate</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
        </div>
    </section>
    """


def _generate_attempts_explorer(attempts: List[Dict]) -> str:
    """Generate attempts explorer with filtering."""
    # Get unique probe names for filter
    probe_names = sorted(set(a['probe'] for a in attempts))
    probe_options = "".join([
        f'<option value="{html.escape(probe)}">{html.escape(probe)}</option>'
        for probe in probe_names
    ])
    
    rows_html = "".join([
        f"""
        <tr class="attempt-row" data-probe="{html.escape(attempt['probe'])}" data-status="{'fail' if attempt['is_vulnerable'] else 'pass'}" onclick="toggleRow('{attempt['uuid']}')" style="cursor: pointer;">
            <td>{attempt['seq']}</td>
            <td>{html.escape(attempt['probe'].split('.')[-1])}</td>
            <td style="max-width: 400px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{html.escape(attempt['prompt'][:100])}</td>
            <td>
                <span class="{'status-fail' if attempt['is_vulnerable'] else 'status-pass'}">
                    {'✗ Fail' if attempt['is_vulnerable'] else '✓ Pass'}
                </span>
            </td>
            <td>{'N/A' if not attempt['detector_scores'] else f"{max(attempt['detector_scores'].values(), default=0.0):.3f}"}</td>
        </tr>
        <tr id="details-{attempt['uuid']}" class="details-row" style="display: none;">
            <td colspan="5" style="background: var(--bg-secondary); padding: 20px;">
                <strong>Full Prompt:</strong>
                <div class="prompt-text" style="margin: 10px 0;">{html.escape(attempt['prompt'])}</div>
                <strong>Response:</strong>
                <div class="response-text" style="margin: 10px 0;">{html.escape(attempt['response'])}</div>
                {f"<strong>Goal:</strong> {html.escape(attempt['goal'])}" if attempt['goal'] else ''}
                {f"<div style='margin-top: 10px;'><strong>Detector Scores:</strong> {', '.join([f'{k}: {v:.3f}' for k, v in attempt['detector_scores'].items()])}</div>" if attempt['detector_scores'] else ''}
            </td>
        </tr>
        """
        for attempt in attempts  # Show ALL attempts now
    ])
    
    return f"""
    <section class="section">
        <h2 class="section-title">🔬 Detailed Results Explorer</h2>
        
        <div class="filters">
            <div class="filter-group">
                <label class="filter-label">Search</label>
                <input type="search" id="search-filter" placeholder="Search prompts/responses..." onkeyup="filterAttempts()" style="width: 300px;">
            </div>
            
            <div class="filter-group">
                <label class="filter-label">Status</label>
                <select id="status-filter" onchange="filterAttempts()">
                    <option value="">All</option>
                    <option value="pass">Pass</option>
                    <option value="fail">Fail</option>
                </select>
            </div>
            
            <div class="filter-group">
                <label class="filter-label">Probe</label>
                <select id="probe-filter" onchange="filterAttempts()">
                    <option value="">All Probes</option>
                    {probe_options}
                </select>
            </div>
        </div>
        
        <p id="visible-count" style="margin-bottom: 15px; color: var(--text-secondary); font-weight: 600;">
            Showing {len(attempts)} of {len(attempts)} attempts
        </p>
        <p style="margin-bottom: 15px; color: var(--text-secondary); font-size: 0.9rem;">
            💡 Tip: Click rows to expand and see full prompt/response details
        </p>
        
        <!-- Pagination Controls (Top) -->
        <div class="pagination">
            <div class="pagination-info">
                <span id="page-info">Page 1 of 1</span>
            </div>
            
            <div class="pagination-controls">
                <label style="font-size: 0.85rem; color: var(--text-secondary); margin-right: 10px;">
                    Rows per page:
                    <select id="page-size" onchange="changePageSize()" class="page-size-select">
                        <option value="25">25</option>
                        <option value="50" selected>50</option>
                        <option value="100">100</option>
                        <option value="200">200</option>
                    </select>
                </label>
                
                <button id="prev-page" onclick="previousPage()" class="page-button">← Previous</button>
                <div id="page-numbers" style="display: flex; gap: 5px;"></div>
                <button id="next-page" onclick="nextPage()" class="page-button">Next →</button>
            </div>
        </div>
        
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>Seq</th>
                        <th>Probe</th>
                        <th>Prompt Preview</th>
                        <th>Status</th>
                        <th>Max Score</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
        </div>
        
        <!-- Pagination Controls (Bottom) -->
        <div class="pagination">
            <div class="pagination-info">
                <span style="font-size: 0.85rem; color: var(--text-secondary);">
                    Jump to page: <input type="number" id="jump-page" min="1" 
                           style="width: 70px; padding: 6px 10px; border: 1px solid var(--border-color); border-radius: 4px; font-size: 0.85rem;"
                           onkeypress="if(event.key==='Enter') {{ const page = parseInt(this.value); if(page > 0) goToPage(page); }}">
                </span>
            </div>
            
            <div class="pagination-controls">
                <button onclick="previousPage()" class="page-button">← Previous</button>
                <div id="page-numbers-bottom" style="display: flex; gap: 5px;"></div>
                <button onclick="nextPage()" class="page-button">Next →</button>
            </div>
        </div>
    </section>
    """


def _generate_config_section(config: Dict) -> str:
    """Generate collapsible configuration section."""
    config_items = "".join([
        f"<div><strong>{key}:</strong> {html.escape(str(value))}</div>"
        for key, value in config.items()
    ])
    
    return f"""
    <section class="section">
        <button class="collapsible">⚙️ Configuration Details</button>
        <div class="collapsible-content">
            <div style="padding: 20px; background: var(--bg-secondary); border-radius: 4px; margin-top: 10px;">
                {config_items}
            </div>
        </div>
    </section>
    """
